### ISSUE TITLE
Create a standard pre-commit hook to require safe attribute

### ISSUE THREAD

**Issue by tim-schilling** [aspiredu/django-safemigrate#39]
We wrote a simple regex pre-commit hook that's extremely crude. It works well enough for us, but the library should probably have something a bit better.

```python
"""
Search our application's migrations are using django_safemigrate.

This is fairly rudimentary and won't work if the class doesn't explicitly inherit
from ``Migration``.
"""

import os
import re
import sys

MIGRATION_PATTERN = re.compile(r"class\s+(?P<MigrationClass>\w+)\s?\(.*Migration\):")
MIGRATION_FILE_PATTERN = re.compile(r"^\d{4}_.+\.py$")

MISSING_SAFE_MESSAGE = (
    "{file_path}: {migration_class} is missing the 'safe' attribute.\n"
)
FAILURE_MESSAGE = (
    "\n"
    "Add the following to the migration class:\n"
    "from django_safemigrate import Safe"
    "class Migration(migrations.Migration):\n"
    "    safe = Safe.before_deploy\n"
    "\n"
    "You can also use the following:\n"
    "    safe = Safe.always\n"
    "    safe = Safe.after_deploy\n"
)


def find_migration_files(directory):
    for root, _, files in os.walk(directory):
        for file in files:
            file_is_migration = MIGRATION_FILE_PATTERN.match(file)
            if file_is_migration and file.endswith(".py"):
                yield os.path.join(root, file)


def validate_migrations():
    success = True
    for file_path in find_migration_files("."):
        # Strip the leading ./ it's a byproduct of os.walk on the current directory
        file_path = file_path[2:] if file_path.startswith("./") else file_path
        with open(file_path, "r") as f:
            content = f.read()

        match = MIGRATION_PATTERN.search(content)
        if match:
            migration_class = match.group("MigrationClass")
            if "safe = Safe." not in content:
                success = False
                sys.stdout.write(
                    MISSING_SAFE_MESSAGE.format(
                        file_path=file_path, migration_class=migration_class
                    )
                )
    if not success:
        sys.stdout.write(FAILURE_MESSAGE)
    return success


if __name__ == "__main__":
    if not validate_migrations():
        sys.exit(1)
```

Then in the yaml:

```yml
repos:
  - repo: local
    hooks:
    -   id: require-safe-migrations
        name: Require migrations to use django_safemigrate
        entry: python -m devops.linters.require_safe_migrations
        language: system
        pass_filenames: false
```
